# Change these first
owner: extratone # Your GitHub organization or username, where this repository lives
repo: cutup # The name of this repository

sites:
  - name: RoutineHub
    url: https://www.routinehub.co
  - name: Shortcuts Directory
    url: https://shortcuts.directory
  - name: Matthew Cassinelli
    url: http://matthewcassinelli.com
  - name: iCloud Sharing (Siri Shortcuts)
    url: https://www.icloud.com/shortcuts/6418f65c0153408086cf15a5378c2e04

status-website:
theme: dark
name: Cutup
  introTitle: "An uptime monitor for the Siri Shortcuts community."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/extratone/cutup
    - title: More Shortucts Resources: https://shortcuts.directory

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
